function initialize_watch_items()
	ScriptHost:AddWatchForCode("UpdateEarlyMissionCount", "EarlyMissionChecks", updateMissionCounts)
	ScriptHost:AddWatchForCode("UpdateLateMissionCount", "LateMissionChecks", updateMissionCounts)
	ScriptHost:AddWatchForCode("UpdateEarlyOutlawCount", "EarlyOutlawChecks", updateMissionCounts)
	ScriptHost:AddWatchForCode("UpdateLateOutlawCount", "LateOutlawChecks", updateMissionCounts)
	ScriptHost:AddWatchForCode("GoalDialga", "goal_dialga", updateItemGrid)
	ScriptHost:AddWatchForCode("GoalDarkrai", "goal_darkrai", updateItemGrid)
	ScriptHost:AddWatchForCode("ProgressiveSkyPeak", "ProgressiveSkyPeakMode", updateItemGrid)
	ScriptHost:AddWatchForCode("RandomSkyPeak", "AllRandomSkyPeakMode", updateItemGrid)
	ScriptHost:AddWatchForCode("UnlockAllSkyPeak", "UnlockAllSkyPeakMode", updateItemGrid)
	ScriptHost:AddWatchForCode("SpecialExclude", "ExcludeSpecial", updateItemGrid)
	ScriptHost:AddWatchForCode("SpecialSanity", "SpecialEpisodeSanity", updateItemGrid)
	ScriptHost:AddWatchForCode("CursedAegis", "CursedAegisCave", updateItemGrid)
	ScriptHost:AddWatchForCode("LongLocationsChange", "LongLocations", updateItemGrid)
	ScriptHost:AddWatchForCode("ProgressiveRecruitItems", "ProgressiveRecruitItems", updateItemGrid)
	ScriptHost:AddWatchForCode("UpdateSpindaDrinks", "SpindaDrinks", spindaDrinks)
	ScriptHost:AddWatchForCode("UpdateSpindaDrinksEvents", "DrinkEvents", spindaDrinksEvent)
	ScriptHost:AddWatchForCode("Recruit-em All", "RecruitAll", updateMap)
end